package model;

/**
 * Created by Julian on 2015-12-26.
 */
public enum Awakening {

    ENHANCE_ATK, ENHANCE_HP, ENHANCE_RCV,
    REDUCE_FIRE, REDUCE_WATER, REDUCE_WOOD, REDUCE_LIGHT_, REDUCE_DARK,
    ENHANCE_ORB_FIRE, ENHANCE_ORB_WATER, ENHANCE_ORB_WOOD, ENHANCE_ORB_LIGHT_, ENHANCE_ORB_DARK,
    ENHANCE_ROW_FIRE, ENHANCE_ROW_WATER, ENHANCE_ROW_WOOD, ENHANCE_ROW_LIGHT_, ENHANCE_ROW_DARK,
    AUTO_RCV,
    RCV_BIND,
    EXTEND_TIME,
    SKILL_BOOST,
    TWO_PRONG_ATK,
    RESIST_BIND, RESIST_DARK, RESIST_JAMMER, RESIST_POISON, RESIST_SKILL_BIND

}
